"""Back to initial migration.

Revision ID: 19837a91edca
Revises: 135a46d27051
Create Date: 2024-08-31 01:06:34.001037

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '19837a91edca'
down_revision = '135a46d27051'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('resume', schema=None) as batch_op:
        batch_op.drop_column('text')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('resume', schema=None) as batch_op:
        batch_op.add_column(sa.Column('text', sa.TEXT(), nullable=False))

    # ### end Alembic commands ###
