"""Add text column to Resume model

Revision ID: 200e54fdedf2
Revises: 19837a91edca
Create Date: 2024-08-31 01:30:19.594176

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '200e54fdedf2'
down_revision = '19837a91edca'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('resume', schema=None) as batch_op:
        batch_op.add_column(sa.Column('extracted_text', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('resume', schema=None) as batch_op:
        batch_op.drop_column('extracted_text')

    # ### end Alembic commands ###
