"""Add feedback_response column to Resume model

Revision ID: 51256541e4ba
Revises: 888139a4c80d
Create Date: 2024-09-10 22:51:28.848830

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '51256541e4ba'
down_revision = '888139a4c80d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('resume', schema=None) as batch_op:
        batch_op.add_column(sa.Column('feedback_response', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('resume', schema=None) as batch_op:
        batch_op.drop_column('feedback_response')

    # ### end Alembic commands ###
