"""Add roast_response column to Resume model

Revision ID: 888139a4c80d
Revises: 25af43768a6b
Create Date: 2024-09-10 20:26:49.393812

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '888139a4c80d'
down_revision = '25af43768a6b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('resume', schema=None) as batch_op:
        batch_op.add_column(sa.Column('roast_response', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('resume', schema=None) as batch_op:
        batch_op.drop_column('roast_response')

    # ### end Alembic commands ###
