"""empty message

Revision ID: a74505729eb2
Revises: 
Create Date: 2024-12-11 08:45:42.991160

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a74505729eb2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('resume',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(length=128), nullable=False),
    sa.Column('data', sa.LargeBinary(), nullable=False),
    sa.Column('extracted_text', sa.Text(), nullable=True),
    sa.Column('candidate_name', sa.String(length=128), nullable=False),
    sa.Column('roast_response', sa.Text(), nullable=True),
    sa.Column('feedback_response', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('resume')
    # ### end Alembic commands ###
