"""Added Cover Letter Response column to save the cover letter

Revision ID: ca86b654a131
Revises: b05d02e1f7bb
Create Date: 2025-01-25 09:14:10.582832

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ca86b654a131'
down_revision = 'b05d02e1f7bb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('resume', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cover_letter_response', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('resume', schema=None) as batch_op:
        batch_op.drop_column('cover_letter_response')

    # ### end Alembic commands ###
